# Oefeningen op sorteren
## Oef1
Hoe kan ik ervoor zorgen dat de array *arr* gesorteerd wordt in onderstaande code. De output moet dus het volgende zijn: (meerdere oplossingen mogelijk)
```
[ 9  9 10 21 44 44 66 70 78 86]
```
1. np.sort(arr)
1. np.sorted(arr)
1. arr.sort()
1. sorted(arr)
1. arr = np.sort(arr)

In [ ]:
import numpy as np
rng = np.random.default_rng(42)
arr = rng.integers(1, 101, size=(10))
#Wat moet je hier invullen om te sorteren?
print(arr)


## Oef2
Hoe kan ik de array omgekeerd sorteren (van groot naar klein)? (meerdere antwoorden mogelijk)

Je moet dus de volgende output krijgen:
```
[86 78 70 66 44 44 21 10  9  9]
```
1. arr.sort(kind='reverse')
1. arr[::-1].sort()
1. arr.sort()[::-1]
1. arr = np.sort(arr)[::-1]
1. arr = np.sort(arr, kind='reverse')
1. arr = arr[np.argsort(-arr)]


In [ ]:
import numpy as np
rng = np.random.default_rng(42)
arr = rng.integers(1, 101, size=(10))
print(arr)
#wat moet je hier invullen om omgekeerd te sorteren?
print(arr)



# Uitleg waarom arr[::-1].sort() de array omgekeerd sorteert
(met dank aan [How does NumPy in-place sort work on views?](https://stackoverflow.com/questions/74986826/how-does-numpy-in-place-sort-work-on-views))
## Een view op een array
Een view is een andere manier om een array te bekijken. We zouden het kunnen zien als een filter die over de oorspronkelijke array wordt gezet. Met 'filter' bedoel ik hier "een andere manier om de array" te bekijken. Dus niet noodzakelijk in de betekenis van "een aantal elementen eruit filteren".

In de volgende code maken we een array met 4 integers die elk 1 byte (8 bits) lang zijn. Met een view kunnen we die array bekijken als een array die np.int16 elementen bevat.(2 bytes of 16 bits). Nu zien we dat de array nog maar 2 elementen bevat. Want met 4 bytes kunnen we maar 2 integers maken die elk 2 bytes lang zijn.

Een view heeft een attribuut *base*. Dat vormt de koppeling met de oorspronkelijke array. Wanneer we de *base* van de view bekijken, zien we de oorspronkelijke array terug.

In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3], dtype=np.uint8)
print('Een array met 4 np.int8 elementen:')
print(f'{arr=}')
arr_als_int16 = arr.view(dtype=np.int16)
print('Een view op de array die de inhoud interpreteert als np.int16')
print(f'{arr_als_int16=}')
print('Een view heeft een "basis-array":')
print(f'{arr_als_int16.base=}')

## De oorspronkelijke array 'overschrijven'
In de volgende code heb ik geen aparte variabele gemaakt voor de view. De variabele *arr* verwijst hier naar de view. Ik ben de toegang tot de oorspronkelijke array dus kwijt.

Alhoewel, niet echt. Want de oorspronkelijke array zit nog steeds in het geheugen en via het *base*-attribuut, zien we nog steeds de oorspronkelijke array met 4 np.int8 elementen.

In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3], dtype=np.uint8)
print('Een array met 4 np.int8 elementen:')
print(f'{arr=}')
arr = arr.view(dtype=np.int16)
print('\nEen view op de array die de inhoud interpreteert als np.int16')
print(f'{arr=}')
print('\nDe view heeft een attribuut "base" waarmee de inhoud als np.int8 wordt geïnterpreteerd:')
print(f'{arr.base=}')

## Een array sorteren
De view *arr_vw* bekijkt de array omgekeerd. Wanneer we de oorspronkelijke array *in-place* sorteren (van klein naar groot), zien we dat de view de gegevens van groot naar klein toont.

Dit is hetzelfde als
1. een gesorteerde array maken (met np.sort(arr))
1. op die gesorteerde array een view zetten die de informatie omgekeerd toont

In [ ]:
import numpy as np

arr = np.array([3, 1, 2])
print('De array:')
print(f'{arr=}')
print('\nEen view die de array omgekeerd bekijkt:')
arr_vw = arr[::-1]
print(f'{arr_vw=}')
print('\nDe base van die view:')
print(f'{arr_vw.base=}')
print('\nWe sorteren de oorspronkelijke array "in-place":')
arr.sort()
print(f'{arr=}')
print('\nDe view ziet er nu zo uit:')
print(f'{arr_vw=}')
print('\nDeze view gebruiken is hetzelfde als:')
print(f'{np.sort(arr)[::-1]=}')


In [ ]:
arr = np.array([3, 1, 2])
arr[::-1].sort()
print(f'{arr=}')

## Een array sorteren via de view
In plaats van de array *in-place* te sorteren, kunnen we ook de view *in-place* sorteren. Daardoor wordt de view op de array oplopend gesorteerd.

Maar, aangezien de view de elementen van de *base*-array in omgekeerde volgorde toont, is de base-array nu aflopend gesorteerd.

In [ ]:
import numpy as np

arr = np.array([3, 1, 2])
print('De array:')
print(f'{arr=}')
print('\nEen view die de array omgekeerd bekijkt:')
arr_vw = arr[::-1]
print(f'{arr_vw=}')
print('\nWe sorteren de view (niet de array) oplopend "in-place":')
arr_vw.sort()
print(f'{arr_vw=}')
print('\nDaardoor is de oorspronkelijke array aflopend gesorteerd:')
print(f'{arr=}')
print("\nDit is hetzelfde als arr[::-1].sort():")
arr = np.array([3, 1, 2])
arr[::-1].sort()
print(f'{arr=}')


## En wanneer we het uitsplitsen?
De volgende code: `arr[::-1].sort()` sorteert de array aflopend. We hebben net gezien hoe dat komt. Maar stel dat we dit in twee stappen uitvoeren. Is de array dan nog steeds aflopend gesorteerd?

De variabele *arr* is niet aflopend gesorteerd. Maar we kunnen nog steeds aan de oorspronkelijke array via *arr.base*. En die is wel aflopend gesorteerd.


In [ ]:
import numpy as np

arr = np.array([3, 1, 2])
print('De array:')
print(f'{arr=}')
arr = arr[::-1]
print('\nEen view die de array omgekeerd bekijkt(arr=arr[::-1]):')
print(f'{arr=}')
print('\nWe sorteren de view "in-place" (arr.sort()):')
arr.sort()
print(f'{arr=}')
print('\nDe oorspronkelijke array kan echter nog steeds via "base" aangesproken worden:')
print(f'{arr.base=}')

## Probeer eens te raden wat de volgende code doet
Nu u volledig ingewijd bent in de geheimen van NumPy-views en sorteringen, kunt u zeker raden wat onderstaande code doet.

In [ ]:
import numpy as np
arr = np.array([3, 1, 2, 4, 0])
arr[:3].sort()
print(arr)
arr = np.array([3, 1, 2, 4, 0])
arr = np.sort(arr[::-1])
print(arr)

## Oef3
Hoe kan ik in het volgende programma de namen afdrukken in deze volgorde:
```
['Kathleen' 'Kristel' 'Karen']
```
1. namen = leeftijden.sort()
1. namen = voornamen.sort()
1. namen = geboortedatums.sort()
1. namen = voornamen[np.argsort(leeftijden)]
1. namen = leeftijden[np.argsort(voornamen)]
1. namen = voornamen[np.argsort(geboortedatums)]




In [ ]:
import numpy as np
def bereken_leeftijden(geboortedatums, refdatum):
  leeftijden = (refdatum - geboortedatums).astype('timedelta64[Y]')
  return leeftijden.astype(int)

voornamen = np.array(['Karen', 'Kristel', 'Kathleen'])
geboortedatums = np.array(['1974-10-28', '1975-12-10', '1978-06-18'], dtype=np.datetime64)
leeftijden = bereken_leeftijden(geboortedatums, np.datetime64('2025-12-09'))
#wat moeten we hier invullen?
print(namen)

## Oef4
Wat is de default waarde van de parameter *axis* in de sort()-functie?

1. 0
1. 1
1. -1

In [ ]:
import numpy as np
rng = np.random.default_rng(42)
arr = rng.integers(1, 101, size=(3,2))
print(arr)
arr.sort(axis=-1)
print(arr)

## Oef5
Hoe kan ik de array op de eerste kolom sorteren? Het resultaat zou er als volgt moeten uitzien:
```
[[ 9 78]
 [44 86]
 [66 44]]
```
1. arr = np.sort(arr[:, 0], axis=1)
1. arr = arr[np.argsort(arr, axis=0)]
1. arr = arr[np.argsort(arr[:, 0])]
1. arr = arr[np.argsort(arr[1, :])]



In [ ]:
import numpy as np
rng = np.random.default_rng(42)
arr = rng.integers(1, 101, size=(3,2))
print(arr)
#Wat moet je hier invullen om te sorteren op de eerste kolom?
print(arr)


## Oef6
Hoe kan ik de array op de tweede rij sorteren? De output moet er dus als volgt uitzien:
```
[[78  9]
 [44 66]
 [86 44]]
```
1. arr = arr[np.argsort(arr[1, :])]
1. arr = arr[:, np.argsort(arr[1, :])]
1. arr = arr[np.argsort(arr[1, :]), :]



In [ ]:
import numpy as np
rng = np.random.default_rng(42)
arr = rng.integers(1, 101, size=(3,2))
print(arr)
#Wat moeten we hier invullen om te sorteren op de tweede rij?
print(arr)

## Oef7
NumPy heeft geen *groupby*-functie (pandas wel). De functie *gemiddelde_per_groep* moet het gemiddelde van de waarden in kolom 1 berekenen per groep van dezelfde waarden in kolom 0. De functie werkt echter niet want er zitten 4 fouten in.

In SQL zou dit zijn: SELECT kol0, avg(kol1) FROM tabel GROUP BY kol0

De output die je zou moeten krijgen is:
```
oorspronkelijke array:
[[ 1 72]
 [ 1 79]
 [ 2 52]
 [ 3 13]
 [ 3 84]
 [ 1 46]
 [ 2 51]
 [ 2 38]
 [ 1 19]
 [ 2 93]
 [ 3 79]
 [ 1 65]
 [ 3 41]]

arr na stap1: sorteer arr op de eerste kolom
[[ 1 72]
 [ 1 79]
 [ 1 46]
 [ 1 19]
 [ 1 65]
 [ 2 51]
 [ 2 38]
 [ 2 52]
 [ 2 93]
 [ 3 13]
 [ 3 84]
 [ 3 79]
 [ 3 41]]

skip na stap2: genereer indexen waar kolom1 van waarde verandert:
[4 8]

skip na stap3: zet positie om naar index en voeg op eerste positie van skip een 0 toe
[0 5 9]

resultaat na stap4: tel de waarden in de tweede kolom op per skipwaarde:
[281 234 217]

lengtes na stap5: maak skip klaar om de lengtes van de groepen te berekenen:
[5 4 4]

keys na stap7: maak array met unieke groepwaarden:
[1 2 3]

gemiddelde per waarde in kolom1:
[[ 1.   56.2 ]
 [ 2.   58.5 ]
 [ 3.   54.25]]
```



In [ ]:
import numpy as np
def gemiddelde_per_groep(arr):
  #stap1: sorteer arr op de eerste kolom
  arr = arr[np.argsort(arr[:, 0])]
  print('\narr na stap1: sorteer arr op de eerste kolom')
  print(arr)
  #stap2: genereer indexen waar kolom1 van waarde verandert
  skip = arr[1:, 0] - arr[:-1,0]
  skip = np.nonzero(skip)
  print('\nskip na stap2: genereer indexen waar kolom1 van waarde verandert:')
  print(skip)
  skip += 1
  #stap3: zet positie om naar index en voeg op eerste positie van skip een 0 toe
  skip = np.insert(skip,0, 0)
  print('\nskip na stap3: zet positie om naar index en voeg op eerste positie van skip een 0 toe')
  print(skip)
  #stap4: tel de waarden in de tweede kolom op per skipwaarde
  resultaat = np.add.reduceat(arr[:, 0], skip)
  print('\nresultaat na stap4: tel de waarden in de tweede kolom op per skipwaarde:')
  print(resultaat)
  #stap5: maak skip klaar om de lengtes van de groepen te berekenen
  skip = np.append(skip, len(arr)-1)
  lengtes = skip[1:] - skip[:-1]
  print('\nlengtes na stap5: maak skip klaar om de lengtes van de groepen te berekenen:')
  print(lengtes)
  #stap6: bereken het gemiddelde van elke groep
  resultaat = resultaat / lengtes
  #stap7: maak array met unieke groepwaarden
  keys = np.unique(arr[:, 0])
  print('\nkeys na stap7: maak array met unieke groepwaarden:')
  print(keys)
  resultaat = np.hstack([keys, resultaat])
  return resultaat
rng = np.random.default_rng(42)
arr = rng.integers(1, 101, size=(3,2))
rng = np.random.default_rng(42)
arr1 = np.array([1, 2, 3])
arr1 = np.tile(arr1, (4, 1))
arr1 = np.ravel(arr1, order='F')
arr1 = np.append(arr1, 1)
rng.shuffle(arr1)
arr2 = rng.integers(1, 101, size=(arr1.size))
arr = np.column_stack([arr1, arr2])
#print(arr)
print('oorspronkelijke array:')
print(arr)
gemiddelde_per_kolom1 = gemiddelde_per_groep(arr)
print('\ngemiddelde per waarde in kolom1:')
print(gemiddelde_per_kolom1)



# Oplossingen
## Oef1
We kunnen de array zelf sorteren met arr.sort() en we krijgen een gesorteerde array terug met arr=np.sort(). Dus antwoorden 3 en 5.
## Oef2
We kunnen het resultaat van een sortering omgekeren (arr = np.sort(arr)[::-1]), maar we kunnen ook argsort() gebruiken om de negatieve array te sorteren en de indexen te gebruiken (arr = arr[np.argsort(-arr)]). Het antwoord arr[::-1].sort() is ook correct. Door te sorteren via de view (die de elementen in omgekeerde volgorde zet), sorteren we de oorspronkelijke array ook omgekeerd. (antwoorden 2, 4 en 6)
## Oef3
We moeten voornamen terugkrijgen, dus de array die we moeten sorteren is *voornamen*. De sortering gebeurt op basis van de leeftijd, dus namen = voornamen[np.argsort(leeftijden)] (antwoord 4)
## Oef4
Er wordt gesorteerd over de laatste dimensie, dus -1 (antwoord 3)
## Oef5
We hebben de indexen nodig die gesorteerd zijn op kolom 0: arr = arr[np.argsort(arr[:, 0])] (antwoord 3)
## Oef6
De kolommen moeten verplaatst worden, dus de indexen moeten bij de kolommen staan: arr = arr[:, np.argsort(arr[1, :])] (antwoord 2)

## Oef7
Je moest de volgende zaken aanpassen:
* na stap2: vervang   skip = np.nonzero(skip) door skip = np.nonzero(skip)[0] omdat het resultaat anders een tuple is (van 1 element, namelijk de NumPy array die we nodig hebben)
* na stap4: vervang resultaat = np.add.reduceat(arr[:, 0], skip) door resultaat = np.add.reduceat(arr[:, 1], skip) omdat je de functie wil toepassen op kolom 1 en niet op kolom 0
* na stap5: vervang skip = np.append(skip, len(arr)-1) door skip = np.append(skip, len(arr)) omdat de laatste waarde 1 meer moet zijn dan de laatste index om het correcte aantal elementen te berekenen voor de laatste groep (aantal elementen in de laatste groep is 4)
* na stap7: vervang  resultaat = np.hstack([keys, resultaat]) door resultaat = np.column_stack([keys, resultaat]) omdat je de arrays als kolommen naast elkaar wil.


```
import numpy as np
def groepeer(arr):
  #stap1: sorteer arr op de eerste kolom
  arr = arr[np.argsort(arr[:, 0])]
  print('\narr na stap1: sorteer arr op de eerste kolom')
  print(arr)
  #stap2: genereer indexen waar kolom1 van waarde verandert
  skip = arr[1:, 0] - arr[:-1,0]
  skip = np.nonzero(skip)[0]
  print('\nskip na stap2: genereer indexen waar kolom1 van waarde verandert:')
  print(skip)
  skip += 1
  #stap3: zet positie om naar index en voeg op eerste positie van skip een 0 toe
  skip = np.insert(skip,0, 0)
  print('\nskip na stap3: zet positie om naar index en voeg op eerste positie van skip een 0 toe')
  print(skip)
  #stap4: tel de waarden in de tweede kolom op per skipwaarde
  resultaat = np.add.reduceat(arr[:, 1], skip)
  print('\nresultaat na stap4: tel de waarden in de tweede kolom op per skipwaarde:')
  print(resultaat)
  #stap5: maak skip klaar om de lengtes van de groepen te berekenen
  skip = np.append(skip, len(arr))
  lengtes = skip[1:] - skip[:-1]
  print('\nlengtes na stap5: maak skip klaar om de lengtes van de groepen te berekenen:')
  print(lengtes)
  #stap6: bereken het gemiddelde van elke groep
  resultaat = resultaat / lengtes
  #stap7: maak array met unieke groepwaarden
  keys = np.unique(arr[:, 0])
  print('\nkeys na stap7: maak array met unieke groepwaarden:')
  print(keys)
  resultaat = np.column_stack([keys, resultaat])
  #resultaat = np.hstack([keys, resultaat])
  return resultaat
rng = np.random.default_rng(42)
arr = rng.integers(1, 101, size=(3,2))
rng = np.random.default_rng(42)
arr1 = np.array([1, 2, 3])
arr1 = np.tile(arr1, (4, 1))
arr1 = np.ravel(arr1, order='F')
arr1 = np.append(arr1, 1)
rng.shuffle(arr1)
arr2 = rng.integers(1, 101, size=(arr1.size))
arr = np.column_stack([arr1, arr2])
#print(arr)
print('oorspronkelijke array:')
print(arr)
gemiddelde_per_kolom1 = groepeer(arr)
print('\ngemiddelde per waarde in kolom1:')
print(gemiddelde_per_kolom1)
```

