#Oefeningen op arrays maken in NumPy
##Oef1
Vertrek van de onderstaande code. Wat moet je invullen om de volgende output te krijgen:
```
[[0 1 2]
 [3 4 5]
 [6 7 8]]
```
1) arr.reshape(3, -1)
1) arr.resize(3, -1)
1) arr = arr. reshape(3, -1)
1) arr = arr.resize(3, -1)

In [ ]:
import numpy as np
arr = np.arange(9)
#wat moet je hier invullen?
print(arr)

##Oef2
De volgende code geeft een fout.Hoe kan ik die fout wegkrijgen?

1) arr = arr.reshape(3, 3)
1) arr = arr.resize(9).reshape(3, -1)
1) arr = arr.reshape(-1, -1)
1) geen van deze oplossingen werkt

In [ ]:
import numpy as np
arr = np.arange(10)
arr = arr.reshape(3, -1) #wat moet ik hier zetten
print(arr)

##Oef3
Wat moet ik invullen in de onderstaande code om de volgende output te krijgen? (meerdere antwoorden mogelijk)

```
[10 11 12 13 14]
```
1) arr2 = np.full_like(arr, 10)
1) arr2 = np.full_like(arr, 5)
1) arr2 = 10
1) arr2 = np.full_like(10, arr)
1) arr2 = np.full_like(5, arr)

In [ ]:
import numpy as np
arr = np.arange(5)
#Wat moet ik hier invullen?
print(arr + arr2)

##Oef4
Wat is de *shape* van de array *arr* in de onderstaande code

1) (10,)
1) (9,)
1) (11,)

In [ ]:
import numpy as np
arr = np.linspace(1, 10, 9)

##Oef5
Wat is het grootst mogelijke getal dat afgedrukt kan worden met de onderstaande code.

1) 9.0
1) 10.0
1) 8.875
1) dat kunnen we niet weten

In [ ]:
import numpy as np
rng = np.random.default_rng()
arr = np.linspace(1, 10, 9)
keuze = rng.choice(arr, size=1, replace=False)
print(keuze[0])

##Oef6
Wat moeten we invullen in de volgende code om als *shape* (5, 2) te krijgen? (meerdere antwoorden mogelijk)

1) arr3 = np.vstack([arr1, arr2])
1) arr3 = np.hstack([arr1, arr2])
1) arr3 = np.column_stack([arr1, arr2])
1) arr3 = np.stack([arr1, arr2], axis=0)
1) arr3 = np.stack([arr1, arr2], axis=1)

In [ ]:
import numpy as np
arr1 = np.arange(1, 6)
arr2 = np.arange(11, 16)
#Wat moet je hier invullen?
print(arr3.shape)

##Oef7
Wat is het verschil in de volgende code tussen `arr1 = np.split(arr, [1])` en `arr1 = np.split(arr, 1)`

1) er is geen verschil
1) met [1] is de shape van arr1[0] gelijk aan (1, 3) en met 1 is het (3, 3)
1) met [1] is de shape van arr1[0] gelijk aan (3, 3) en met 1 is het (1, 3)
1) met [1] geeft de code een fout en met 1 niet
1) met 1 geeft de code een fout en met [1] niet

In [ ]:
import numpy as np
arr = np.arange(9).reshape(-1, 3)
#arr1 = np.split(arr, [1])
#arr1 = np.split(arr, 1)
arr1[0].shape

##Oef8
Wat is de waarde van arr[0] in de volgende code (zoek voor alle zekerheid eens op wat np.empty() doet)

1) Dat kunnen we niet op voorhand zeggen
1) 0
1) nan (not-a-number)
1) None

In [ ]:
import numpy as np
arr = np.empty(4)
print(arr)

##Oef9
Hoeveel punten worden er geplot met de onderstaande code.

1) 10
1) 9
1) genoeg om een vloeiende curve te tekenen
1) de code geeft een fout (er wordt dus niets geplot)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(10)
y = x ** 2
plt.plot(x, y)
plt.show()

##Oef10
We hebben gezien dat we met np.linalg.inv(arr) de inverse van een matrix kunnen berekenen en vervolgens met de @-operator een vermenigvuldiging kunnen uitvoeren om de oplossing van een stelsel te bekomen.

Gebruik dit eens om het volgende stelsel op te lossen. Wat is de uitkomst?

$$x_1 + x_2 + 2 x_3 = 7\\
3x_1 - 2x_2 +x_3=1\\
2x_1 + 2x_2 + 4x_3 = 12$$

1) x1=1,x2=2, x3=2
1) x1=0,x2=3, x3=2
1) Je krijgt een foutmelding wanneer je de inverse probeert te gebruiken.

##Extra oef
we hebben gezien hoe we een stelsel van vergelijkingen kunnen oplossen door de rijen van een matrix van elkaar af te trekken. De code die we gezien hebben was heel specifiek voor een bepaalde matrix. Schrijf eens een functie waarmee je de code in de volgende stelsels kunt oplossen. Je moet de volgende twee oplossingen krijgen (opmerking: de methode zoals wij ze gezien hebben werkt niet wanneer je een 0 zou uitkomen op een diagonaal. Dan moet je twee rijen wisselen. Maar daar moet je in eerste instantie geen rekening mee houden) :
(zie eventueel [zie Gauss-Jordan eliminatie](https://nl.wikipedia.org/wiki/Gauss-Jordaneliminatie))
```
[ 2. -1.  3.]
[2. 1.]
```

In [ ]:
import numpy as np

#Vul deze functie aan
def los_vergelijkingen_op(matrix, vector):
  pass

arr_A = np.array([2, 2, -1, 1, 2, 3, 1, -1, 2], dtype=np.float64).reshape(3, -1)
vec_y = np.array([-1, 9, 9])
oplossing = los_vergelijkingen_op(arr_A, vec_y)
print(oplossing)
arr_A = np.array([1, 1, 3, -2], dtype=np.float64).reshape(2, -1)
vec_y = np.array([3, 4])
oplossing = los_vergelijkingen_op(arr_A, vec_y)
print(oplossing)

#Oplossingen
##Oef1
arr = arr.reshape(3, -1)(antwoord 3). We moeten *reshape()* gebruiken want we willen alleen de vorm (de dimensies) wijzigen en niet de grootte (dat is wat resize() doet)
##Oef2
Geen van deze oplossingen werkt(antwoord 4). Het tweede antwoord komt het dichtste in de buurt. De volgende code werkt wel (resize() wijzigt de grootte en geeft None terug):
```
arr.resize(9)
arr = arr.reshape(3, -1)
```
##Oef3
arr2 = np.full_like(arr, 10)(antwoord 1) en arr2 = 10 (antwoord 3). Het eerste antwoord is redelijk logisch. Het derde antwoord zorgt ervoor dat de optelling`arr + 10` wordt.
##Oef4
(9,) (antwoord 2). Het derde argument van *np.linspace* bepaalt hoeveel getallen er gegenereerd moeten worden. De afstand tussen twee opeenvolgende getallen wordt berekend (bij *np.arange* geven we als derde argument de afstand tussen de opeenvolgende getallen)
##Oef5
10 (antwoord 2). Standaard is het tweede argument van *np.linspace* inclusief.
##Oef6
arr3 = np.column_stack([arr1, arr2]) (antwoord 3) en arr3 = np.stack([arr1, arr2], axis=1) (antwoord 5)
##Oef7
met [1] is de shape van arr1[0] gelijk aan (1, 3) en met 1 is het (3, 3)(antwoord 2).

Wanneer we een list meegeven ([1]), zijn dat de indexen waarop gesplitst moet worden. Wanneer we een getal meegeven (1), zeggen we in hoeveel gelijke delen de array moet gesplitst worden.
##Oef8
Dat kunnen we niet op voorhand zeggen(antwoord 1). De functie *np.empty* voorziet plaats in het geheugen, maar initialiseert de waarden niet. Je krijgt standaard de informatie te zien die (toevallig) op die plaats in het geheugen staat. Wanneer we als type een (Pytyon) object meegeven, worden de elementen geïnitialiseerd op None. We gebruiken *np.empty* wanneer we de waarden achteraf invullen.
##Oef9
De code geeft een fout(antwoord 4). *np.linspace* is niet hetzelfde als *np.arange*. We moeten altijd een begin- en eindwaarde invullen.
##Oef10
Je krijgt een foutmelding omdat je de inverse probeert te gebruiken (antwoord 3). De matrix heeft geen inverse. Dus je kunt het stelsel niet oplossen. (de coëfficiënten van de derde rij zijn een veelvoud van de coëfficiënten van de eerste rij)
##Extra oef
```
import numpy as np

def los_vergelijkingen_op(matrix, vector):
  stelsel = np.column_stack([matrix, vector])
  for pivot in range(stelsel.shape[0]):
    stelsel[pivot] /= stelsel[pivot, pivot]

    for index in range(pivot + 1, stelsel.shape[0]):
      stelsel[index] -= stelsel[index, pivot] * stelsel[pivot]
  for pivot in range(stelsel.shape[0] - 1, -1, -1):
    for index in range(pivot - 1, -1, -1):
      stelsel[index] -= stelsel[index, pivot] * stelsel[pivot]
  return stelsel[:, -1]

arr_A = np.array([2, 2, -1, 1, 2, 3, 1, -1, 2], dtype=np.float64).reshape(3, -1)
vec_y = np.array([-1, 9, 9])
oplossing = los_vergelijkingen_op(arr_A, vec_y)
print(oplossing)
arr_A = np.array([1, 1, 3, -2], dtype=np.float64).reshape(2, -1)
vec_y = np.array([3, 4])
oplossing = los_vergelijkingen_op(arr_A, vec_y)
print(oplossing)
```

