#Oefeningen op UFuncs
##Oef1
Vertrek van onderstaande code. Hoe kun je de getallen in elke kolom optellen? Het resultaat zou er dus als volgt moeten uitzien (meerdere antwoorden mogelijk):
```
[12 15 18]
```
1) print(np.sum(arr1))
1) print(np.add(arr1))
1) print(np.add.reduce(arr1))
1) print(np.add.accumulate(arr1))



In [ ]:
import numpy as np
arr1 = np.arange(1, 10).reshape(3, -1)
print(arr1)
#Wat moet je hier invullen om [12 15 18] te krijgen?

##Oef2
Hoe kun je in onderstaande code ervoor zorgen dat de getallen in elke rij worden opgeteld? Het resultaat zou er dus als volgt moeten uitzien (meerdere antwoorden mogelijk):
```
[ 6 15 24]
```
1) np.sum(arr1, axis=0)
1) np.add.reduce(arr1, axis=0)
1) np.sum(arr1, axis=1)
1) np.add.reduce(arr1, axis=1)




In [ ]:
import numpy as np
arr1 = np.arange(1, 10).reshape(3, -1)
print(arr1)
#Wat moet je hier invullen om [ 6 15 24] te krijgen?

##Oef3
Kijk eens met %timeit of er een verschil in snelheid is tussen sum(arr1) en np.sum(arr1)
1) ze zijn beiden (ongeveer) even snel
1) np.sum is veel sneller
1) sum is veel sneller

In [ ]:
import numpy as np
arr1 = np.arange(10_000)

##Oef4
Is er een verschil in snelheid tussen np.add(arr1, arr2) en np.add(arr1, arr2, out=arr1)?
1) ze zijn beiden (ongeveer) even snel
1) np.add(arr1, arr2) is veel sneller
1) np.add(arr1, arr2, out=arr1) is veel sneller

In [ ]:
import numpy as np
arr1 = np.arange(10_000)
arr2 = np.arange(10_000)
#meet de tijd voor np.add(arr1, arr2)
#meet de tijd voor np.add(arr1, arr2? out=arr1)

##Oef5
Wat is het snelste volgens de volgende code:  arr1 + arr2 of arr1 += arr1
1) Ze zijn beiden (ongeveer) even snel
1) arr1 + arr2 is sneller
1) arr1 += arr2 is sneller
1) we kunnen de tijd van arr1 += arr2 niet meten met deze code

In [ ]:
import numpy as np
arr1 = np.arange(10_000)
arr2 = np.arange(10_000)
%timeit arr1 + arr2
%timeit arr1+= arr2

##Oef6
Welk van de twee statements met np.add() moet je gebruiken om bij de even getallen 2 op te tellen. Het resultaat zou dus het volgende moeten zijn:
```
[ 1  4  3  6  5  8  7 10  9 12]
```
1) arr1 = np.add(arr1, arr2, where=arr1 % 2 == 0)
1) np.add(arr1, arr2, out = arr1, where=arr1 % 2 == 0)
1) Beide statements werken


In [ ]:
import numpy as np
arr1 = np.arange(1, 11)
print(arr1)
arr2 = np.full_like(arr1, 2)
#arr1 = np.add(arr1, arr2, where=arr1 % 2 == 0)
#np.add(arr1, arr2, out = arr1, where=arr1 % 2 == 0)
print(arr1)

##Oef7
Hoe kan ik de drie elementen van arr2 optellen bij de laatste drie elementen van arr1? Het resultaat moet er dus als volgt uitzien (meerdere antwoorden mogelijk):
```
[1 2 4 6 8]
```
1) np.add.at(arr1,range(-3, 0), arr2)
1) arr1 = np.add.at(arr1,list(range(-3, 0)), arr2)
1) np.add.at(arr1,range(-3, 0), arr2, out=arr1)
1) arr1 = np.add.at(arr1, [-3, -2, -1], arr2)


In [ ]:
import numpy as np
arr1 = np.arange(1, 6)
print('arr1: ', arr1)
arr2 = np.arange(1, 4)
print('arr2:', arr2)
#wat moeten we hier invullen?
#np.add.at(arr1,range(-3, 0), arr2)              #antwoord1
#arr1 = np.add.at(arr1,list(range(-3, 0)), arr2) #antwoord2
#np.add.at(arr1,range(-3, 0), arr2, out=arr1)    #antwoord3
#arr1 = np.add.at(arr1, [-3, -2, -1], arr2)      #antwoord4
print(arr1)

##Oef8
Ik wil de getallen in arr1 per 7 (bijvoorbeeld de 7 dagen van een week) optellen. Wat moet ik invullen als *indices*? Het resultaat zou dus de volgende reeks moeten zijn:
```
[ 28  77 126 175]
```
1) indices = range(0, 29, 7)
2) indices = range(0, 28, 7)
3) indices = range(0, 27, 7)
4) geen van deze antwoorden werkt

In [ ]:
import numpy as np
arr1 = np.arange(1, 29)
print('arr1: ', arr1)
#wat moeten we hier invullen?
#indices = range(0, 29, 7)     #antwoord 1
#indices = range(0, 28, 7)    #antwoord 2
#indices = range(0, 27, 7)    #antwoord 3
print('indices:',list(indices))
arr1 = np.add.reduceat(arr1,indices)
print(arr1)

## Oef9
In de onderstaande code tellen we de 5 elementen van arr2 op bij de eerste 5 elementen van arr1 (in commentaar). Hoe zou je dit nog kunnen schrijven?

Je moet dus het volgende resultaat krijgen
```
[ 0  3  6  9 12  5  6  7  8  9]
```

1) arr1 = arr1[range(5)] + arr2
1) arr1 = arr1[0, 1, 2, 3, 4] + arr2
1) arr1 += arr2
1) arr1[range(5)] += arr2
1) geen van deze oplossingen werkt

In [ ]:
import numpy as np
arr1 = np.arange(10)
arr2 = np.arange(0, 10, 2)
print(f'{arr1=}')
print(f'{arr2=}')
#np.add.at(arr1, range(5), arr2) # hoe zou je dit nog kunnen schrijven
print(arr1)


##Oef10
In de onderstaande code is np.add.at gebruikt om de 5 getallen van arr2 op te tellen bij de getallen in de posities 3, 4, 7, 8 en 9. Hoe zou je dit schrijven met de +=-operator?

In [ ]:
import numpy as np
arr1 = np.arange(10)
arr2 = np.arange(0, 10, 2)
print(f'{arr1=}')
print(f'{arr2=}')
#np.add.at(arr1, [3, 4, 7, 8, 9], arr2)
#hoe zou je dit met de += operator schrijven
print(arr1)

#Oplossingen UFuncs
##Oef1
np.add.reduce(arr1) (antwoord 3) is correct. Bij een array van 2 dimensies wordt er standaard per rij opgeteld.
##Oef2
np.sum(arr1, axis=1) (antwoord 3) en np.add.reduce(arr1, axis=1 (antwoord 4) zijn correct.
##Oef3
np.sum is veel sneller (antwoord 2)
##Oef4
Ze zijn beiden ongeveer even snel(antwoord 1). Normaal is de versie met het out-argument een klein beetje sneller. Wanneer je grotere arrays gebruikt (bijvoorbeeld 10.000.000) zul je waarschijnlijk het verschil al beter zien.
##Oef5
We kunnen de tijd van arr1 += arr2 niet meten (antwoord 4) want we krijgen een fout. Wanneer we de correcte code gebruiken (global arr1;arr1+=arr2) zien we dat ze allebei weer ongeveer even snel zijn (arr1+=arr2 is iets sneller)
##Oef6
np.add(arr1, arr2, out = arr1, where=arr1 % 2 == 0) (antwoord 2). Een where-argument zonder out-argument heeft niet veel zin omdat we dan niet weten welke waarde de elementen zullen hebben waar de where-voorwaarde False is.
##Oef7
np.add.at(arr1,range(-3, 0), arr2) (antwoord 1). np.add.at() geeft altijd None terug. De at-functie heeft ook [geen out-parameter](https://numpy.org/doc/stable/reference/generated/numpy.ufunc.at.html#numpy.ufunc.at)
##Oef8
indices = range(0, 28, 7) (antwoord 2). Dit is hetzelfde als indices = range(0, arr1.size, 7). Als indices hebben we de waarden [0, 7, 14, 21] nodig. Dat zijn de *ranges*: 0:7, 7:14, 14:21 en 21: . Maar ook antwoord 3 is correct want dat genereert dezelfde indices.
##Oef9
arr1[range(5)] += arr2 (antwoord 4). We zetten de indexen van np.add.at tussen de vierkante haakjes van arr1
##Oef10
arr1[[3, 4, 7, 8, 9]] += arr2 (vergeet de dubbele vierkante haakjes niet)