# Vraag 1
In de volgende Pythoncode bevat de array *temperaturen* de maximumtemperaturen voor de dagen van maandag tot en met zondag voor drie steden:
|Stad      |Maandag  |Dinsdag  |Woensdag  |Donderdag  |Vrijdag  |Zaterdag  |Zondag | 
|----------|--------:|--------:|---------:|----------:|--------:|---------:|-------:|
|Antwerpen |     -4  |     6   |      4   |      1    |     1   |     7    |   -4   |
|Leuven    |      5  |    -2   |     -4   |      2    |     9   |     6    |    6   |
|Mechelen  |      5  |     6   |      2   |     -4    |     7   |     1    |    2   |

Vul de functie *hoogste_temperatuur* aan zodat het programma de hoogste temperatuur in de array afdrukt.

Verwachte output:  
Hoogste temperatuur= 9°C

Plak jouw code voor de functie *hoogste_temperatuur* in de Syntra-leeromgeving.

In [ ]:
import numpy as np
dagen = np.array(["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag", "Zondag"])
steden = np.array(["Antwerpen", "Leuven", "Mechelen"])
rng = np.random.default_rng(42)
temperaturen = rng.integers(-5, 10, (steden.size, dagen.size))
#print('De temperaturen:', temperaturen, sep='\n')

def hoogste_temperatuur(temp):
    return None   #vul hier de juiste code in.

print(f"Hoogste temperatuur= {hoogste_temperatuur(temperaturen)}°C")

# Vraag 2
We vertrekken van dezelfde code. Zorg ervoor dat de functie *gemiddelde_temperatuur_in_mechelen* de gemiddelde temperatuur van de laatste rij teruggeeft. 

Verwachte output:  
Gemiddelde temperatuur in Leuven = 2.7°C

Plak jouw code voor de functie *gemiddelde_temperatuur_in_mechelen* in de Syntra-leeromgeving.

In [ ]:
import numpy as np
dagen = np.array(["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag", "Zondag"])
steden = np.array(["Antwerpen", "Leuven", "Mechelen"])
rng = np.random.default_rng(42)
temperaturen = rng.integers(-5, 10, (steden.size, dagen.size))
#print('De temperaturen:', temperaturen, sep='\n')

def gemiddelde_temperatuur_in_mechelen(temp):
    return None #vul hier de juiste code in.

print(f"Gemiddelde temperatuur in Mechelen = {gemiddelde_temperatuur_in_mechelen(temperaturen):.1f}°C")

# Vraag 3
En nog een vraag bij deze code. Zorg ervoor dat de functie *laagste_temperatuur_op_maandag* de laagste temperatuur in de eerste kolom teruggeeft. 

Verwachte output:  
Laagste temperatuur op maandag = -4°C

Plak jouw code voor de functie *laagste_temperatuur_op_maandag* in de Syntra-leeromgeving.

In [ ]:
import numpy as np
dagen = np.array(["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag", "Zondag"])
steden = np.array(["Antwerpen", "Leuven", "Mechelen"])
rng = np.random.default_rng(42)
temperaturen = rng.integers(-5, 10, (steden.size, dagen.size))
#print('De temperaturen:', temperaturen, sep='\n')

def laagste_temperatuur_op_maandag(temp):
    return None #vul hier de juiste code in.

print(f"Laagste temperatuur op maandag = {laagste_temperatuur_op_maandag(temperaturen)}°C")

# Vraag 4
Er is een fout gebeurd met de metingen in Leuven. Alle temperaturen van Leuven moeten met 1 verhoogd worden. De output moet er als volgt uitzien:

Verwachte output:  
```
De correcte temperatuurmatrix:
    [[-4  6  4  1  1  7 -4]
     [ 6 -1 -3  3 10  7  7]
     [ 5  6  2 -4  7  1  2]]
```
Plak jouw code voor *corrigeer_leuven* in de Syntra leeromgeving

In [ ]:
import numpy as np
dagen = np.array(["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag", "Zondag"])
steden = np.array(["Antwerpen", "Leuven", "Mechelen"])
rng = np.random.default_rng(42)
temperaturen = rng.integers(-5, 10, (steden.size, dagen.size))
#print('De temperaturen:', temperaturen, sep='\n')

#Vul de functie aan zodat de temperatuur van de tweede rij met 1 wordt verhoogd.
def corrigeer_leuven(temp):
    
    return None

temperaturen = corrigeer_leuven(temperaturen)
print('De correcte temperatuurmatrix:', temperaturen, sep='\n')

# Vraag 5
Vul de functie *gemiddelde_temperatuur_per_dag* aan zodat je een array met de gemiddelde temperaturen voor elke dag teruggeeft. 

De verwachte output is:
```
   Maandag   Dinsdag  Woensdag Donderdag   Vrijdag  Zaterdag    Zondag
       2.0       3.3       0.7      -0.3       5.7       4.7       1.3
```

Plak jouw oplossing voor de functie *gemiddelde_termperatuur_per_dag* in de Syntra leeromgeving

In [ ]:
import numpy as np
dagen = np.array(["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag", "Zondag"])
steden = np.array(["Antwerpen", "Leuven", "Mechelen"])
rng = np.random.default_rng(42)
temperaturen = rng.integers(-5, 10, (steden.size, dagen.size))
#print('De temperaturen:', temperaturen, sep='\n')

#Pas de functie aan zodat ze een array met de gemiddelde temperaturen voor elke dag teruggeeft
def gemiddelde_temperatuur_per_dag(temps):
    return None

for dag in dagen:
    print(f"{dag:>10s}", end='')
print()
for temp in gemiddelde_temperatuur_per_dag(temperaturen):
    print(f"{temp:10.1f}", end='')

# Vraag 6
Vul de functie *hoogste_temperatuur_op_weekdag* aan zodat ze voor elke gemeente de hoogste temperatuur op een weekdag teruggeeft.

De verwachte output is:  
Antwerpen: 6°C  
Leuven: 9°C  
Mechelen: 7°C  

Plak jouw versie van *hoogste_temperatuur_op_weekdag* in de Syntra leeromgeving.

In [ ]:
import numpy as np
dagen = np.array(["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag", "Zondag"])
steden = np.array(["Antwerpen", "Leuven", "Mechelen"])
rng = np.random.default_rng(42)
temperaturen = rng.integers(-5, 10, (steden.size, dagen.size))
#print('De temperaturen:', temperaturen, sep='\n')

def hoogste_temperatuur_op_weekdag(temp):
    return None

for stad, temp in zip(steden, hoogste_temperatuur_op_weekdag(temperaturen)):
    print(f"{stad}: {temp}°C")


# Vraag 7
De volgende code download de Titanic dataset van Kaggle. Je vindt de beschrijving van die dataset [hier](https://www.kaggle.com/datasets/yasserh/titanic-dataset).

In [1]:
from zipfile import ZipFile
import numpy as np
import requests
DATA_ZIP = 'data.zip'
data = requests.get('https://www.kaggle.com/api/v1/datasets/download/yasserh/titanic-dataset')
with open(DATA_ZIP, 'wb') as f:
  f.write(data.content)
with open(DATA_ZIP, 'rb') as f:
  ZipFile(f).extractall()

Vul de code aan met berekeningen voor *aantal_overleefd_eerste_klasse* en *percentage_overleefd_eerste_klasse* zodat je de volgende output krijgt:

In eerste klasse hebben 136 passagiers de ramp overleefd.  
Dat is 63% van de passagiers in eerste klasse.

Plak je code in de Syntra leeromgeving

In [ ]:
TITANIC_CSV = 'Titanic-Dataset.csv'
# lees hier de data die je nodig hebt 
# schrijf de correcte expressies voor de volgende twee variabelen
aantal_overleefd__eerste_klasse = None 
percentage_overleefd_eerste_klasse = None 
print(f"In eerste klasse hebben {aantal_overleefd__eerste_klasse} passagiers de ramp overleefd.")
print(f"Dat is {percentage_overleefd_eerste_klasse:.0f}% van de passagiers in eerste klasse." )

# Vraag 8
Volgens de film 'Titanic' van James Cameron waren Rose DeWitt en Jack Dawson aan boord van de Titanic. Vul de code en de functie *test_namen* aan zodat je antwoorden kunt geven op de volgende vragen:
- was er iemand met de naam Cameron aan boord? (dat was inderdaad het geval, maar zoek het uit met Numpy)
- was er iemand met de naam Dawson aan boord? (dat zul je zelf moeten uitzoeken)

Verwachte output:
```
Cameron was boord
Dawson was ...
```
Plak je volledige programma in de Syntra leeromgeving.

In [ ]:
import numpy as np
TITANIC_CSV = 'Titanic-Dataset.csv'
#Lees hier de data die je nodig hebt
namen = None
#Vul de functie aan zodat ze de juiste output afdrukt.
def test_naam(namenlijst, naam):
    pass

test_naam(namen, 'Cameron')
test_naam(namen, 'Dawson')

# Vraag 9
We keren terug naar de code van de eerste vraag. Vul de functie *gemiddelde_temperatuur_in* aan zodat de returnwaarde de gemiddelde temperatuur in *stad* teruggeeft. Wanneer er geen data is over die stad, moet de code een exception geven. 

Verwachte output:  
De gemiddelde temperatuur in Leuven was 3.1°C  
De gemiddelde temperatuur in Mechelen was 2.7°C  
Voor Brussel hebben we geen temperatuur.

Trek je niets aan van de *with warnings.catch_warnings*-constructie. Sommige mogelijke oplossingen (want er zijn meerdere mogelijkheden) genereren een RuntimeWarning. De *with warnings.catch_warnings*-constructie zorgt ervoor dat die RuntimeWarning niet wordt getoond. (het zou kunnen dat jouw oplossing geen RuntimeWarning genereert. Dus trek je er niets van aan).
Plak jouw code voor de functie *gemiddelde_temperatuur_in* in de Syntra-leeromgeving.

In [ ]:
import numpy as np
import warnings
dagen = np.array(["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag", "Zondag"])
steden = np.array(["Antwerpen", "Leuven", "Mechelen"])
rng = np.random.default_rng(42)
temperaturen = rng.integers(-5, 10, (steden.size, dagen.size))
#print('De temperaturen:', temperaturen, sep='\n')

#Pas de volgende functie aan
def gemiddelde_temperatuur_in(arr_temps, arr_steden, locatie):
    return None

with warnings.catch_warnings():
    warnings.simplefilter('ignore')
    for stad in ('Leuven', 'Mechelen', 'Brussel'):
        try:
            gemiddelde_temperatuur = gemiddelde_temperatuur_in(temperaturen, steden, stad)
            print(f'De gemiddelde temperatuur in {stad} was {gemiddelde_temperatuur:.1f}°C')
        except IndexError:
            print(f'Voor {stad} hebben we geen temperatuur.')

# Vraag 10
Je weet ondertussen dat er een passagier met de naam Cameron aan boord was. Schrijf Numpy code waarmee je toont wat de volledige naam was van die passagier en hoeveel zij moest betalen (*fare*).

Verwachte output:
Passagier "Cameron, Miss. Clear Annie" betaalde £21.0.

Plak je volledige programma in de Syntra leeromgeving.

# Vraag 11
De onderstaande code maakt een bestand met de (verwachte) verkoopcijfers voor elke dag van de maand februari 2026. Ter info: 1 februari 2026 valt op een zondag. Maar op zondag is de winkel gesloten, dus vandaar dat het verkoopcijfer voor elke zondag 0 is.

Gevraagd: lees dit bestand met NumPy en genereer een lijst met de som van de verkopen voor elke week. Zorg dat je de volgende output genereert:
```
Op zaterdag 2026-02-07 is er gedurende de hele week voor €12487 verkocht.
Op zaterdag 2026-02-14 is er gedurende de hele week voor €12586 verkocht.
Op zaterdag 2026-02-21 is er gedurende de hele week voor €12433 verkocht.
Op zaterdag 2026-02-28 is er gedurende de hele week voor €13517 verkocht.
```
Plak je code in de Syntra leeromgeving.

In [4]:
from datetime import date, timedelta
verkopen = [0, 2547, 2309, 1877, 1866, 2717, 1171, 0, 1402, 1188, 2052,
       2951, 2471, 2522, 0, 2572, 2026, 1256, 2679, 1900, 2000, 0,
       1365, 2853, 2563, 2287, 1804, 2645]
dagen = [date(2026, 2, 1) + timedelta(dag) for dag in range(28)]
MAANDOMZET_CSV = 'maandomzet.csv'
with open(MAANDOMZET_CSV, mode='w') as f:
    print('dag;verkoopcijfer', file=f)
    for dag, cijfer in zip(dagen, verkopen):
        print(f"{dag};{cijfer}", file=f)