# Vraag 1

In [1]:
import numpy as np
dagen = np.array(["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag", "Zondag"])
steden = np.array(["Antwerpen", "Leuven", "Mechelen"])
rng = np.random.default_rng(42)
temperaturen = rng.integers(-5, 10, (steden.size, dagen.size))
#print('De temperaturen:', temperaturen, sep='\n')

def hoogste_temperatuur(temp):
    return np.max(temp)

print(f"Hoogste temperatuur= {hoogste_temperatuur(temperaturen)}°C")

Hoogste temperatuur= 9°C


# Vraag 2

In [2]:
import numpy as np
dagen = np.array(["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag", "Zondag"])
steden = np.array(["Antwerpen", "Leuven", "Mechelen"])
rng = np.random.default_rng(42)
temperaturen = rng.integers(-5, 10, (steden.size, dagen.size))
#print('De temperaturen:', temperaturen, sep='\n')

def gemiddelde_temperatuur_in_mechelen(temp):
    return np.mean(temp[-1]) #vul hier de juiste code in.

print(f"Gemiddelde temperatuur in Leuven = {gemiddelde_temperatuur_in_mechelen(temperaturen):.1f}°C")

Gemiddelde temperatuur in Leuven = 2.7°C


# Vraag 3

In [ ]:
import numpy as np
dagen = np.array(["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag", "Zondag"])
steden = np.array(["Antwerpen", "Leuven", "Mechelen"])
rng = np.random.default_rng(42)
temperaturen = rng.integers(-5, 10, (steden.size, dagen.size))
#print('De temperaturen:', temperaturen, sep='\n')

def laagste_temperatuur_op_maandag(temp):
    return np.min(temp[:, 0]) #vul hier de juiste code in.

print(f"Laagste temperatuur op maandag = {laagste_temperatuur_op_maandag(temperaturen)}°C")

Laagste temperatuur op maandag = -4°C


# Vraag 4

In [ ]:
import numpy as np
dagen = np.array(["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag", "Zondag"])
steden = np.array(["Antwerpen", "Leuven", "Mechelen"])
rng = np.random.default_rng(42)
temperaturen = rng.integers(-5, 10, (steden.size, dagen.size))
#print('De temperaturen:', temperaturen, sep='\n')

#Vul de functie aan zodat de temperatuur van de tweede rij met 1 wordt verhoogd.
def corrigeer_leuven(temp):
    temp[[1]] += 1
    return temp

temperaturen = corrigeer_leuven(temperaturen)
print('De correcte temperatuurmatrix:', temperaturen, sep='\n')

De correcte temperatuurmatrix:
[[-4  6  4  1  1  7 -4]
 [ 6 -1 -3  3 10  7  7]
 [ 5  6  2 -4  7  1  2]]


# Vraag 5

In [8]:
import numpy as np
dagen = np.array(["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag", "Zondag"])
steden = np.array(["Antwerpen", "Leuven", "Mechelen"])
rng = np.random.default_rng(42)
temperaturen = rng.integers(-5, 10, (steden.size, dagen.size))
#print('De temperaturen:', temperaturen, sep='\n')

#Pas de functie aan zodat ze een array met de gemiddelde temperaturen voor elke dag teruggeeft
def gemiddelde_temperatuur_per_dag(temps):
    return np.mean(temps, axis=0)

for dag in dagen:
    print(f"{dag:>10s}", end='')
print()
for temp in gemiddelde_temperatuur_per_dag(temperaturen):
    print(f"{temp:10.1f}", end='')

   Maandag   Dinsdag  Woensdag Donderdag   Vrijdag  Zaterdag    Zondag
       2.0       3.3       0.7      -0.3       5.7       4.7       1.3

# Vraag 6

In [3]:
import numpy as np
dagen = np.array(["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag", "Zondag"])
steden = np.array(["Antwerpen", "Leuven", "Mechelen"])
rng = np.random.default_rng(42)
temperaturen = rng.integers(-5, 10, (steden.size, dagen.size))
#print('De temperaturen:', temperaturen, sep='\n')

def hoogste_temperatuur_op_weekdag(temp):
    return np.max(temp[:, :5], axis=1)

for stad, temp in zip(steden, hoogste_temperatuur_op_weekdag(temperaturen)):
    print(f"{stad}: {temp}°C")

Antwerpen: 6°C
Leuven: 9°C
Mechelen: 7°C


# Vraag 7

In [4]:
TITANIC_CSV = 'Titanic-Dataset.csv'
is_overleefd = np.genfromtxt(TITANIC_CSV, dtype=np.int8, delimiter=',', skip_header=True, usecols=1)
klasse = np.genfromtxt(TITANIC_CSV, dtype=np.int8, delimiter=',', skip_header=True, usecols=2)
aantal_overleefd__eerste_klasse = np.count_nonzero((is_overleefd==1) &(klasse==1))
percentage_overleefd_eerste_klasse = aantal_overleefd__eerste_klasse / np.count_nonzero(klasse==1) * 100
print(f"In eerste klasse hebben {aantal_overleefd__eerste_klasse} passagiers de ramp overleefd.")
print(f"Dat is {percentage_overleefd_eerste_klasse:.0f}% van de passagiers in eerste klasse." )

In eerste klasse hebben 136 passagiers de ramp overleefd.
Dat is 63% van de passagiers in eerste klasse.


# Vraag 8

In [ ]:
import numpy as np
TITANIC_CSV = 'Titanic-Dataset.csv'
namen = np.genfromtxt(TITANIC_CSV, delimiter=',', skip_header=1, usecols=3, dtype=str)
def test_naam(namenlijst, naam):
    if np.any(namenlijst=='"'+naam):
        print(f"{naam} was aan boord")
    else:
        print(f"{naam} was niet aan boord")

test_naam(namen, 'Cameron')
test_naam(namen, 'Dawson')

Cameron was niet aan boord
Dawson was niet aan boord


# Vraag 9

In [ ]:
import numpy as np
import warnings
dagen = np.array(["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag", "Zondag"])
steden = np.array(["Antwerpen", "Leuven", "Mechelen"])
rng = np.random.default_rng(42)
temperaturen = rng.integers(-5, 10, (steden.size, dagen.size))
#print('De temperaturen:', temperaturen, sep='\n')

#Pas de volgende functie aan
def gemiddelde_temperatuur_in(arr_temps, arr_steden, locatie):
    is_stad = arr_steden == locatie
    if np.count_nonzero(is_stad) == 0:
        raise IndexError()
    return np.mean(arr_temps[is_stad])

with warnings.catch_warnings():
    warnings.simplefilter('ignore')
    for stad in ('Leuven', 'Mechelen', 'Brussel'):
        try:
            gemiddelde_temperatuur = gemiddelde_temperatuur_in(temperaturen, steden, stad)
            print(f'De gemiddelde temperatuur in {stad} was {gemiddelde_temperatuur:.1f}°C')
        except IndexError:
            print(f'Voor {stad} hebben we geen temperatuur.')

3.142857142857143
De gemiddelde temperatuur in Leuven was 3.1°C
2.7142857142857144
De gemiddelde temperatuur in Mechelen was 2.7°C
nan
Voor Brussel hebben we geen temperatuur.


# Vraag 10

In [12]:
from csv import DictReader, DictWriter
TITANIC_CSV = 'Titanic-Dataset.csv'
TITANIC_PSV = 'Titanic.csv'  #puntkomma separated values
with open(TITANIC_CSV, newline='') as f_in:
    reader = DictReader(f_in, delimiter=',')
    with open(TITANIC_PSV, mode='w') as f_out:
        writer = DictWriter(f_out, delimiter=';', fieldnames=reader.fieldnames)
        writer.writeheader()
        for regel in reader:
            writer.writerow(regel)

namen = np.genfromtxt(TITANIC_PSV, delimiter=';', skip_header=1, usecols=3, dtype=str)
prijzen = np.genfromtxt(TITANIC_PSV, delimiter=';', skip_header=1, usecols=-3)
naam = 'Cameron'
is_cameron = np.strings.startswith(namen, naam)
volledige_naam = namen[is_cameron][0]
prijs = prijzen[is_cameron][0]
print(f'Passagier "{volledige_naam}" betaalde £{prijs}.')


Passagier "Cameron, Miss. Clear Annie" betaalde £21.0.


# Vraag 11

In [1]:
import numpy as np
MAANDOMZET_CSV = 'maandomzet.csv'
dagen = np.genfromtxt(MAANDOMZET_CSV, skip_header=1, dtype=np.datetime64, delimiter=';', usecols=0)
verkopen = np.genfromtxt(MAANDOMZET_CSV, skip_header=1, dtype=np.int64, delimiter=';', usecols=1)

verkoop_per_week = verkopen.reshape(-1, 7)
totaal_per_week = np.sum(verkoop_per_week, axis=1)
#alternatief zonder reshape:
#totaal_per_week = np.add.reduceat(verkopen, indices=[0, 7, 14, 21])
for dag, verkoop in zip(dagen[range(6, 29, 7)], totaal_per_week):
    print(f"Op zaterdag {dag} is er gedurende de hele week voor €{verkoop} verkocht.")

Op zaterdag 2026-02-07 is er gedurende de hele week voor €12487 verkocht.
Op zaterdag 2026-02-14 is er gedurende de hele week voor €12586 verkocht.
Op zaterdag 2026-02-21 is er gedurende de hele week voor €12433 verkocht.
Op zaterdag 2026-02-28 is er gedurende de hele week voor €13517 verkocht.


In [6]:
totaal_per_week = np.add.reduceat(verkopen, indices=[0, 7, 14, 21])
totaal_per_week

array([12487, 12586, 12433, 13517])