## Vraag 1
Je krijgt een array met 5 getallen. Toon alleen de positieve getallen van de array, maar zorg dat ze verdubbeld zijn. De output moet er dus als volgt uitzien:
```
[ 4 10  2]
```



In [ ]:
import numpy as np
arr = np.array([2, -1, 5, -2, 1])
#toon alleen de positieve getallen, maar zorg dat ze verdubbeld zijn
print(arr)

## Vraag 2
Je krijgt van mij drie arrays met de voornamen, de achternamen en de geboortedatums van de drie beste zangeressen van de lage landen. (je wist dat je dit soort vraag zou krijgen). De bedoeling is dat je de variabelen *voornamen_sorted*, *achternamen_sorted* en *geboortedatums_sorted* correct invult zodat de zangeressen gesorteerd op achternaam worden getoond. De output moet er dus als volgt uitzien:
```
Kathleen Aerts is geboren op 18-06-1978
Karen Damen is geboren op 28-10-1974
Kristel Verbeke is geboren op 10-12-1975
```



In [ ]:
import numpy as np
from datetime import date
voornamen = np.array(['Karen', 'Kristel', 'Kathleen'])
achternamen = np.array(['Damen', 'Verbeke', 'Aerts'])
geboortedatums = np.array(['1974-10-28', '1975-12-10', '1978-06-18'], dtype=np.datetime64)
#Hoe moet je de volgende 3 statements wijzigen om te sorteren op achternaam
voornamen_sorted = voornamen
achternamen_sorted = achternamen
geboortedatums_sorted = geboortedatums
for voornaam, achternaam, geboortedatum in zip(voornamen_sorted, achternamen_sorted, geboortedatums_sorted):
  print(f'{voornaam} {achternaam} is geboren op {geboortedatum.astype(date).strftime("%d-%m-%Y")}')

## Vraag 3
Je krijgt van mij twee arrays. Ik heb in de code een constructie gezet die we niet gezien hebben (*with warnings.catch_warnings():*). Je moet je daar niet teveel van aantrekken. Die zorgt ervoor dat je geen warning-meldingen krijgt wanneer je de code uitvoert.
Voeg een print-statement toe zodat je het gemiddelde toont van arr1 gedeeld door arr2. Het resultaat moet er als volgt uitzien:
```
2.0
```



In [ ]:
import numpy as np
import warnings
arr_1 = np.array([4.0, 9.0, 0.0, 1.0])
arr_2 = np.array([2.0, 3.0, 0.0, 1.0])

with warnings.catch_warnings():
  warnings.simplefilter('ignore')
  #wat moet je hier schrijven om het gemiddelde van arr_1 gedeeld door arr_2 af te drukken?

## Vraag 4
Het volgende script geeft een fout. Pas de laatste regel aan zodat je de volgende output krijgt:
```
array([[ 6,  9,  9],
       [11,  5,  4]])
```



In [ ]:
import numpy as np
arr_1 = np.array([[1, 4, 4],[8, 2, 1]])
arr_2 = np.array([5, 3])
arr_1 + arr_2             #Hoe moet je dit statement aanpassen om de juiste output te krijgen?

## Vraag 5
Zorg ervoor dat de array gesorteerd wordt op basis van de tweede kolom. Het resultaat moet er dus als volgt uitzien:
```
Oorspronkelijke arr:
 [[ 1  4 -1]
 [ 8  3 -2]
 [ 3  2  5]]
Gesorteerd op tweede kolom:
array([[ 3,  2,  5],
       [ 8,  3, -2],
       [ 1,  4, -1]])
```



In [ ]:
import numpy as np
arr = np.array([[1, 4, -1],[8, 3, -2], [3, 2, 5]])
print('Oorspronkelijke arr:\n', arr)
print('Gesorteerd op tweede kolom:')
arr                                   #sorteer de array op basis van de tweede kolom

## Vraag 6
Pas de laatste regel aan zodat de som van elk van de rijen wordt afgedrukt. Let op bij de afdruk: het resultaat moet als een kolom worden getoond. De output moet er dus als volgt uitzien:

```
arr:
 [[ 1  8  7  5  5  9  1  7]
 [ 3  1  6 10  8  8  8  8]
 [ 6  2  9  5  6  4  2 10]
 [ 8  7  5  9  6  5  5  3]
 [ 1  6  9  1  9  9  3  7]]
De som van de kolommen:
[[43]
 [52]
 [44]
 [48]
 [45]]
```

In [ ]:
import numpy as np
rng = np.random.default_rng(42)
arr = rng.integers(1, 11, size=(5, 8))
print('arr:\n', arr)
print('De som van de kolommen:')
print(arr) #Hoe moet je dit statement aanpassen?